export * from './auth.service';
import { AuthService } from './auth.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './sysLog.service';
import { SysLogService } from './sysLog.service';
export * from './userManagement.service';
import { UserManagementService } from './userManagement.service';
export * from './water.service';
import { WaterService } from './water.service';
export const APIS = [AuthService, ProfileService, SysLogService, UserManagementService, WaterService];
