/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PfpUpdateResponse { 
    /**
     * URL of the uploaded profile picture
     */
    url?: string;
}

