/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SysLogEntryElement } from './sysLogEntryElement';


export interface SysLogEntry { 
    timestamp: string;
    user: string;
    action: string;
    elements: Array<SysLogEntryElement>;
}

