/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterReportDto } from './waterReportDto';


export interface WaterReportDetail { 
    waterReport: WaterReportDto;
    id: number;
    reportedBy?: string;
    reportedAt: string;
}

