/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaterStateDto { 
    fullGallons: number;
    emptyGallons: number;
    waterLevel: number;
    reportedAt: string;
}

