/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterStateDto } from './waterStateDto';


export interface WaterStateDetail { 
    waterState: WaterStateDto;
    id: number;
    reportedBy?: string;
}

