/**
 * ReVIZit API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaterReportKind } from './waterReportKind';


export interface WaterReportDto { 
    kind: WaterReportKind;
    /**
     * The level of water in the gallon, as a percentage. Only applicable for PERCENTAGE reports. 
     */
    value?: number;
    /**
     * The flavour of the new gallon. Only applicable for SWAP reports. 
     */
    flavourId?: number;
}



