/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.revizit.rest.api;

import org.revizit.rest.model.AuthenticationRequest;
import org.revizit.rest.model.AuthenticationResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Auth", description = "Authentication stuff")
public interface AuthApi {

    default AuthApiDelegate getDelegate() {
        return new AuthApiDelegate() {};
    }

    String PATH_IS_AUTHENTICATED = "/auth";
    /**
     * GET /auth : Checks for authentication.
     * Pings the server with the authentication token included as a bearer token to check for its validity. 
     *
     * @return Ok (status code 200)
     *         or Unauthorized (status code 403)
     */
    @Operation(
        operationId = "isAuthenticated",
        summary = "Checks for authentication.",
        description = "Pings the server with the authentication token included as a bearer token to check for its validity. ",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "403", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_IS_AUTHENTICATED
    )
    default ResponseEntity<Void> isAuthenticated(
        
    ) {
        return getDelegate().isAuthenticated();
    }


    String PATH_LOGIN = "/auth/login";
    /**
     * POST /auth/login : Attempts authentication.
     * Submits an username-password authentication request for login purposes. 
     *
     * @param authenticationRequest  (required)
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "login",
        summary = "Attempts authentication.",
        description = "Submits an username-password authentication request for login purposes. ",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthenticationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthenticationResponse> login(
        @Parameter(name = "AuthenticationRequest", description = "", required = true) @Valid @RequestBody AuthenticationRequest authenticationRequest
    ) {
        return getDelegate().login(authenticationRequest);
    }

}
