/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.revizit.rest.api;

import org.revizit.rest.model.ApiError;
import org.springframework.lang.Nullable;
import org.revizit.rest.model.PasswordChangeRequest;
import org.revizit.rest.model.PfpUpdateResponse;
import org.revizit.rest.model.Profile;
import org.revizit.rest.model.ProfileData;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Profile", description = "User profile related stuff")
public interface ProfileApi {

    default ProfileApiDelegate getDelegate() {
        return new ProfileApiDelegate() {};
    }

    String PATH_CHANGE_MY_PASSWORD = "/profile/my/pw";
    /**
     * PUT /profile/my/pw : Changes user password
     * Changes user password.
     *
     * @param passwordChangeRequest  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "changeMyPassword",
        summary = "Changes user password",
        description = "Changes user password.",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProfileApi.PATH_CHANGE_MY_PASSWORD,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> changeMyPassword(
        @Parameter(name = "PasswordChangeRequest", description = "", required = true) @Valid @RequestBody PasswordChangeRequest passwordChangeRequest
    ) {
        return getDelegate().changeMyPassword(passwordChangeRequest);
    }


    String PATH_DELETE_MY_PROFILE = "/profile/my";
    /**
     * DELETE /profile/my : Deletes user profile
     * Deletes user profile.
     *
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "deleteMyProfile",
        summary = "Deletes user profile",
        description = "Deletes user profile.",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ProfileApi.PATH_DELETE_MY_PROFILE
    )
    default ResponseEntity<Void> deleteMyProfile(
        
    ) {
        return getDelegate().deleteMyProfile();
    }


    String PATH_GET_MY_PROFILE = "/profile/my";
    /**
     * GET /profile/my : Get user profile
     *
     * @return Successful operation (status code 200)
     *         or Profile not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getMyProfile",
        summary = "Get user profile",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Profile.class))
            }),
            @ApiResponse(responseCode = "404", description = "Profile not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProfileApi.PATH_GET_MY_PROFILE,
        produces = { "application/json" }
    )
    default ResponseEntity<Profile> getMyProfile(
        
    ) {
        return getDelegate().getMyProfile();
    }


    String PATH_UPDATE_MY_PROFILE = "/profile/my";
    /**
     * PUT /profile/my : Updates user profile
     * Updates user profile.
     *
     * @param profileData  (required)
     * @return Ok (status code 200)
     *         or Error updating profile (status code 400)
     */
    @Operation(
        operationId = "updateMyProfile",
        summary = "Updates user profile",
        description = "Updates user profile.",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Profile.class))
            }),
            @ApiResponse(responseCode = "400", description = "Error updating profile", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProfileApi.PATH_UPDATE_MY_PROFILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Profile> updateMyProfile(
        @Parameter(name = "ProfileData", description = "", required = true) @Valid @RequestBody ProfileData profileData
    ) {
        return getDelegate().updateMyProfile(profileData);
    }


    String PATH_UPDATE_PROFILE_PIC = "/profile/my/picture";
    /**
     * PUT /profile/my/picture : Upload profile picture
     *
     * @param file PNG or JPG image file (optional)
     * @return Profile picture uploaded successfully (status code 200)
     *         or Invalid file format or size (status code 400)
     *         or Unauthorized (status code 401)
     *         or File too large (status code 413)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateProfilePic",
        summary = "Upload profile picture",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile picture uploaded successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PfpUpdateResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid file format or size", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "413", description = "File too large", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProfileApi.PATH_UPDATE_PROFILE_PIC,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<PfpUpdateResponse> updateProfilePic(
        @Parameter(name = "file", description = "PNG or JPG image file") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().updateProfilePic(file);
    }

}
