/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.revizit.rest.api;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.lang.Nullable;
import java.time.OffsetDateTime;
import org.revizit.rest.model.SysLogEntry;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "SysLog", description = "Stuff about application logs")
public interface SysLogApi {

    default SysLogApiDelegate getDelegate() {
        return new SysLogApiDelegate() {};
    }

    String PATH_GET_SYS_LOGS = "/syslog";
    /**
     * GET /syslog : Returns application events.
     * Returns application events between the FROM and TO values, ordered by timestamp. If no  values are provided, today&#39;s events are returned. 
     *
     * @param from The earliest date to include in the result. (optional)
     * @param to The latest date to include in the result. (optional)
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "getSysLogs",
        summary = "Returns application events.",
        description = "Returns application events between the FROM and TO values, ordered by timestamp. If no  values are provided, today's events are returned. ",
        tags = { "SysLog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SysLogEntry.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SysLogApi.PATH_GET_SYS_LOGS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<SysLogEntry>> getSysLogs(
        @Parameter(name = "from", description = "The earliest date to include in the result.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime from,
        @Parameter(name = "to", description = "The latest date to include in the result.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime to
    ) {
        return getDelegate().getSysLogs(from, to);
    }

}
