/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.revizit.rest.api;

import org.revizit.rest.model.ApiError;
import org.springframework.lang.Nullable;
import org.revizit.rest.model.Profile;
import org.revizit.rest.model.UserSelector;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "UserManagement", description = "User management related stuff")
public interface UserManagementApi {

    default UserManagementApiDelegate getDelegate() {
        return new UserManagementApiDelegate() {};
    }

    String PATH_CREATE_USERS = "/umgmt";
    /**
     * POST /umgmt : Creates users by standard file upload
     * Creates users by standard file upload.
     *
     * @param file  (optional)
     * @return Created (status code 201)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "createUsers",
        summary = "Creates users by standard file upload",
        description = "Creates users by standard file upload.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserManagementApi.PATH_CREATE_USERS,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> createUsers(
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().createUsers(file);
    }


    String PATH_DELETE_USER = "/umgmt";
    /**
     * DELETE /umgmt : Deletes a user
     * Deletes a user.
     *
     * @param userSelector  (required)
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "deleteUser",
        summary = "Deletes a user",
        description = "Deletes a user.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = UserManagementApi.PATH_DELETE_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteUser(
        @Parameter(name = "UserSelector", description = "", required = true) @Valid @RequestBody UserSelector userSelector
    ) {
        return getDelegate().deleteUser(userSelector);
    }


    String PATH_FLIP_USER_ROLE = "/umgmt/role";
    /**
     * PUT /umgmt/role : Flips a user&#39;s role
     * Flips a user&#39;s role.
     *
     * @param userSelector  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "flipUserRole",
        summary = "Flips a user's role",
        description = "Flips a user's role.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Profile.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UserManagementApi.PATH_FLIP_USER_ROLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Profile> flipUserRole(
        @Parameter(name = "UserSelector", description = "", required = true) @Valid @RequestBody UserSelector userSelector
    ) {
        return getDelegate().flipUserRole(userSelector);
    }


    String PATH_GET_ALL_USERS = "/umgmt";
    /**
     * GET /umgmt : Returns all users of the application.
     * Returns all users of the application.
     *
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "getAllUsers",
        summary = "Returns all users of the application.",
        description = "Returns all users of the application.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Profile.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserManagementApi.PATH_GET_ALL_USERS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Profile>> getAllUsers(
        
    ) {
        return getDelegate().getAllUsers();
    }


    String PATH_RESET_USER_PASSWORD = "/umgmt/reset";
    /**
     * POST /umgmt/reset : Resets a user&#39;s password
     * Resets a user&#39;s password.
     *
     * @param userSelector  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "resetUserPassword",
        summary = "Resets a user's password",
        description = "Resets a user's password.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserManagementApi.PATH_RESET_USER_PASSWORD,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resetUserPassword(
        @Parameter(name = "UserSelector", description = "", required = true) @Valid @RequestBody UserSelector userSelector
    ) {
        return getDelegate().resetUserPassword(userSelector);
    }


    String PATH_UPDATE_USER = "/umgmt";
    /**
     * PUT /umgmt : Updates user profile
     * Updates user profile.
     *
     * @param profile  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "updateUser",
        summary = "Updates user profile",
        description = "Updates user profile.",
        tags = { "UserManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Profile.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UserManagementApi.PATH_UPDATE_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Profile> updateUser(
        @Parameter(name = "Profile", description = "", required = true) @Valid @RequestBody Profile profile
    ) {
        return getDelegate().updateUser(profile);
    }

}
