/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.revizit.rest.api;

import org.revizit.rest.model.ApiError;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.lang.Nullable;
import java.time.OffsetDateTime;
import org.revizit.rest.model.WaterFlavourDto;
import org.revizit.rest.model.WaterReportDetail;
import org.revizit.rest.model.WaterReportDto;
import org.revizit.rest.model.WaterStateDetail;
import org.revizit.rest.model.WaterStateDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Water", description = "Water related stuff")
public interface WaterApi {

    default WaterApiDelegate getDelegate() {
        return new WaterApiDelegate() {};
    }

    String PATH_APPROVE_WATER_REPORT = "/report/approve";
    /**
     * PUT /report/approve : Approves one or more water reports.
     * Approves one or more water reports. The water reports must be pending approval, form a consecutive list (in chronological order), and must start with the oldest pending report. 
     *
     * @param requestBody  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "approveWaterReport",
        summary = "Approves one or more water reports.",
        description = "Approves one or more water reports. The water reports must be pending approval, form a consecutive list (in chronological order), and must start with the oldest pending report. ",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = WaterApi.PATH_APPROVE_WATER_REPORT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> approveWaterReport(
        @Parameter(name = "request_body", description = "", required = true) @Valid @RequestBody List<Long> requestBody
    ) {
        return getDelegate().approveWaterReport(requestBody);
    }


    String PATH_CREATE_WATER_FLAVOUR = "/flavour";
    /**
     * POST /flavour : Creates a new flavour
     * Creates a new flavour.
     *
     * @param body  (required)
     * @return Created (status code 201)
     *         or Flavour already exists (status code 409)
     */
    @Operation(
        operationId = "createWaterFlavour",
        summary = "Creates a new flavour",
        description = "Creates a new flavour.",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WaterFlavourDto.class))
            }),
            @ApiResponse(responseCode = "409", description = "Flavour already exists")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WaterApi.PATH_CREATE_WATER_FLAVOUR,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<WaterFlavourDto> createWaterFlavour(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody String body
    ) {
        return getDelegate().createWaterFlavour(body);
    }


    String PATH_DEFINE_CURRENT_WATER_STATE = "/water/current";
    /**
     * POST /water/current : Defines the current water state.
     * Explicitly set the current water state. 
     *
     * @param waterStateDto  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     */
    @Operation(
        operationId = "defineCurrentWaterState",
        summary = "Defines the current water state.",
        description = "Explicitly set the current water state. ",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WaterStateDetail.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WaterApi.PATH_DEFINE_CURRENT_WATER_STATE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<WaterStateDetail> defineCurrentWaterState(
        @Parameter(name = "WaterStateDto", description = "", required = true) @Valid @RequestBody WaterStateDto waterStateDto
    ) {
        return getDelegate().defineCurrentWaterState(waterStateDto);
    }


    String PATH_DELETE_WATER_FLAVOUR = "/flavour/{id}";
    /**
     * DELETE /flavour/{id} : Deletes a water flavour.
     * Deletes a water flavour.
     *
     * @param id  (required)
     * @return Ok (status code 200)
     *         or Flavour in use (status code 409)
     */
    @Operation(
        operationId = "deleteWaterFlavour",
        summary = "Deletes a water flavour.",
        description = "Deletes a water flavour.",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "409", description = "Flavour in use")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = WaterApi.PATH_DELETE_WATER_FLAVOUR
    )
    default ResponseEntity<Void> deleteWaterFlavour(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().deleteWaterFlavour(id);
    }


    String PATH_GET_CURRENT_WATER_STATE = "/water/current";
    /**
     * GET /water/current : The current water state.
     * Returns the count of full and empty gallons, as well as the water level in the current gallon. 
     *
     * @return Ok (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getCurrentWaterState",
        summary = "The current water state.",
        description = "Returns the count of full and empty gallons, as well as the water level in the current gallon. ",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WaterStateDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WaterApi.PATH_GET_CURRENT_WATER_STATE,
        produces = { "application/json" }
    )
    default ResponseEntity<WaterStateDto> getCurrentWaterState(
        
    ) {
        return getDelegate().getCurrentWaterState();
    }


    String PATH_GET_PENDING_WATER_REPORTS = "/report";
    /**
     * GET /report : Returns the pending water reports.
     * Returns the pending water reports waiting for approval.
     *
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "getPendingWaterReports",
        summary = "Returns the pending water reports.",
        description = "Returns the pending water reports waiting for approval.",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = WaterReportDetail.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WaterApi.PATH_GET_PENDING_WATER_REPORTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<WaterReportDetail>> getPendingWaterReports(
        
    ) {
        return getDelegate().getPendingWaterReports();
    }


    String PATH_GET_WATER_FLAVOURS = "/flavour";
    /**
     * GET /flavour : Returns all available water flavours.
     * Returns all available water flavours.
     *
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "getWaterFlavours",
        summary = "Returns all available water flavours.",
        description = "Returns all available water flavours.",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = WaterFlavourDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WaterApi.PATH_GET_WATER_FLAVOURS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<WaterFlavourDto>> getWaterFlavours(
        
    ) {
        return getDelegate().getWaterFlavours();
    }


    String PATH_GET_WATER_STATES = "/water";
    /**
     * GET /water : Get historic water states.
     * Returns a list of water states, ordered by date. 
     *
     * @param from The earliest date to include in the result. (optional)
     * @param to The latest date to include in the result. (optional)
     * @return Ok (status code 200)
     *         or Unauthorized (status code 403)
     */
    @Operation(
        operationId = "getWaterStates",
        summary = "Get historic water states.",
        description = "Returns a list of water states, ordered by date. ",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = WaterStateDetail.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WaterApi.PATH_GET_WATER_STATES,
        produces = { "application/json" }
    )
    default ResponseEntity<List<WaterStateDetail>> getWaterStates(
        @Parameter(name = "from", description = "The earliest date to include in the result.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime from,
        @Parameter(name = "to", description = "The latest date to include in the result.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime to
    ) {
        return getDelegate().getWaterStates(from, to);
    }


    String PATH_REJECT_WATER_REPORT = "/report/reject";
    /**
     * PUT /report/reject : Rejects one or more water reports.
     * Rejects one or more water reports. The water reports must be pending approval. 
     *
     * @param requestBody  (required)
     * @return Ok (status code 200)
     *         or Bad request (status code 400)
     */
    @Operation(
        operationId = "rejectWaterReport",
        summary = "Rejects one or more water reports.",
        description = "Rejects one or more water reports. The water reports must be pending approval. ",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = WaterApi.PATH_REJECT_WATER_REPORT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> rejectWaterReport(
        @Parameter(name = "request_body", description = "", required = true) @Valid @RequestBody List<Long> requestBody
    ) {
        return getDelegate().rejectWaterReport(requestBody);
    }


    String PATH_SUBMIT_WATER_REPORT = "/report";
    /**
     * POST /report : Submits a water report.
     * Submits a water report for the current user (if any).
     *
     * @param waterReportDto  (required)
     * @return Ok (status code 200)
     *         or Unauthorized (status code 403)
     */
    @Operation(
        operationId = "submitWaterReport",
        summary = "Submits a water report.",
        description = "Submits a water report for the current user (if any).",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WaterReportDetail.class))
            }),
            @ApiResponse(responseCode = "403", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WaterApi.PATH_SUBMIT_WATER_REPORT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<WaterReportDetail> submitWaterReport(
        @Parameter(name = "WaterReportDto", description = "", required = true) @Valid @RequestBody WaterReportDto waterReportDto
    ) {
        return getDelegate().submitWaterReport(waterReportDto);
    }


    String PATH_UPDATE_WATER_FLAVOUR = "/flavour/{id}";
    /**
     * PUT /flavour/{id} : Updates a water flavour.
     * Updates a water flavour.
     *
     * @param id  (required)
     * @param waterFlavourDto  (required)
     * @return Ok (status code 200)
     */
    @Operation(
        operationId = "updateWaterFlavour",
        summary = "Updates a water flavour.",
        description = "Updates a water flavour.",
        tags = { "Water" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WaterFlavourDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = WaterApi.PATH_UPDATE_WATER_FLAVOUR,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<WaterFlavourDto> updateWaterFlavour(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "WaterFlavourDto", description = "", required = true) @Valid @RequestBody WaterFlavourDto waterFlavourDto
    ) {
        return getDelegate().updateWaterFlavour(id, waterFlavourDto);
    }

}
