@startuml

top to bottom direction
skinparam linetype ortho

entity flavour_request {
  name: text
  submitted_at: timestamp
  submitted_by: integer
  ---
  id: integer
}
entity user_account {
  username: text
  mail_addr: text
  user_pw: text
  user_role: varchar(5)
  inactive: boolean
  reg_token: uuid
  token_exp: timestamp
  ---
  id: integer
}
entity user_profile {
  display_name: varchar(255)
  user_account: integer
  pfp: text
  ---
  id: integer
}
entity water_flavour {
  name: text
  inactive: boolean
  ---
  id: integer
}
entity water_report {
  kind: report_type
  val: integer
  reported_at: timestamp
  reported_by: integer
  approved_at: timestamp
  approved_by: integer
  flavour: integer
  rejected_at: timestamp
  rejected_by: integer
  ---
  id: integer
}
entity water_state {
  empty_cnt: integer
  full_cnt: integer
  curr_pct: integer
  created_at: timestamp
  report: integer
  ---
  id: integer
}

enum report_type {
  ---
  BALLOON_CHANGE
  SET_PERCENTAGE
  BALLOON_REFILL
}

flavour_request  -[plain]-^  user_account          : "submitted_by:id"
water_report     -[plain]-^  user_account          : "approved_by:id"
water_report     -[plain]-^  user_account          : "rejected_by:id"
water_report     -[plain]-^  user_account          : "reported_by:id"
water_report     -[plain]-^  water_flavour         : "flavour:id"
water_state      -[plain]-^  water_report          : "report:id"
report_type     ^-[dashed]-  water_report::kind    : "type def"
user_profile     -[plain]^  user_account          : "user_account:id"
@enduml
