openapi: 3.0.1
info:
  title: ReVIZit API
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication stuff
  - name: Profile
    description: User profile related stuff
paths:

  # Auth
  /auth/login:
    post:
      summary: Attempts authentication.
      description: |
        Submits an username-password authentication request for login purposes.
      tags:
        - Auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
  /auth:
    get:
      summary: Checks for authentication.
      description: |
        Pings the server with the authentication token included as a bearer token to check
        for its validity.
      tags:
        - Auth
      operationId: isAuthenticated
      responses:
        '200':
          description: Ok
        '403':
          description: Unauthorized

  /profile/my:
    get:
      tags:
        - Profile
      summary: Get user profile
      operationId: getMyProfile
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: [ username, password ]
    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
    Profile:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        isAdmin:
          type: boolean
          default: false
      required: [ username, name, isAdmin ]

    ApiError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string
      required: [ status, timestamp ]
