openapi: 3.0.1
info:
  title: ReVIZit API
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication stuff
  - name: Profile
    description: User profile related stuff
  - name: Water
    description: Water related stuff
paths:

  # Auth
  /auth/login:
    post:
      summary: Attempts authentication.
      description: |
        Submits an username-password authentication request for login purposes.
      tags:
        - Auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
  /auth:
    get:
      summary: Checks for authentication.
      description: |
        Pings the server with the authentication token included as a bearer token to check
        for its validity.
      tags:
        - Auth
      operationId: isAuthenticated
      responses:
        '200':
          description: Ok
        '403':
          description: Unauthorized

  /profile/my:
    get:
      tags:
        - Profile
      summary: Get user profile
      operationId: getMyProfile
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /water/current:
    get:
      summary: The current water state.
      tags:
        - Water
      description: |
        Returns the count of full and empty gallons, as well as the water level in the current gallon.
      operationId: getCurrentWaterState
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterStateDto'
        '404':
          description: Not found
    post:
      summary: Defines the current water state.
      tags:
        - Water
      description: |
        Explicitly set the current water state.
      operationId: defineCurrentWaterState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaterStateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterStateDetail'
        '400':
          description: Bad Request

  /water:
    get:
      summary: Get historic water states.
      tags:
        - Water
      description: |
        Returns a list of water states, ordered by date.
      operationId: getWaterStates
      parameters:
        - name: from
          in: query
          description: The earliest date to include in the result.
          required: false
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: The latest date to include in the result.
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterStateDetail'
        '403':
          description: Unauthorized

  /report:
    post:
      summary: Submits a water report.
      description: Submits a water report for the current user (if any).
      operationId: submitWaterReport
      tags:
        - Water
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaterReportDto'
        required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterReportDetail'
        '403':
          description: Unauthorized
    get:
      summary: Returns the pending water reports.
      description: Returns the pending water reports waiting for approval.
      operationId: getPendingWaterReports
      tags:
        - Water
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterReportDetail'
  /report/approve:
    put:
      summary: Approves one or more water reports.
      description: |
        Approves one or more water reports. The water reports must be pending approval, form a
        consecutive list (in chronological order), and must start with the oldest pending report.
      operationId: approveWaterReport
      tags:
        - Water
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /report/reject:
    put:
      summary: Rejects one or more water reports.
      description: |
        Rejects one or more water reports. The water reports must be pending approval.
      operationId: rejectWaterReport
      tags:
        - Water
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /flavour:
    get:
      summary: Returns all available water flavours.
      description: Returns all available water flavours.
      operationId: getWaterFlavours
      tags:
        - Water
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterFlavourDto'
    post:
      summary: Creates a new flavour
      description: Creates a new flavour.
      operationId: createWaterFlavour
      tags:
        - Water
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterFlavourDto'
        '409':
          description: Flavour already exists

  /flavour/{id}:
    delete:
      summary: Deletes a water flavour.
      description: Deletes a water flavour.
      operationId: deleteWaterFlavour
      tags:
        - Water
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ok
        '409':
          description: Flavour in use
    put:
      summary: Updates a water flavour.
      description: Updates a water flavour.
      operationId: updateWaterFlavour
      tags:
        - Water
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaterFlavourDto'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterFlavourDto'

  /flavour/admin/all:
    get:
      summary: Returns all - including inactive - water flavours.
      description: Returns all - including inactive - water flavours.
      operationId: getAllWaterFlavours
      tags:
        - Water
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterFlavourDto'
  /flavour/admin/in-use:
    get:
      summary: Returns the IDs of the water flavours currently in use.
      description: Returns the IDs of the water flavours currently in use.
      operationId: getInUseWaterFlavours
      tags:
        - Water
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /flavour/admin/activate/{id}:
    put:
      summary: Activates an archived water flavour.
      description: Activates an archived water flavour.
      operationId: activateWaterFlavour
      tags:
        - Water
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterFlavourDto'


components:
  schemas:
    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: [ username, password ]
    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
    Profile:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        isAdmin:
          type: boolean
          default: false
      required: [ username, name, isAdmin ]

    ApiError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string
      required: [ status, timestamp ]

    WaterStateDto:
      type: object
      properties:
        fullGallons:
          type: integer
          minimum: 0
          format: int32
          example: 4
        emptyGallons:
          type: integer
          minimum: 0
          format: int32
          example: 3
        waterLevel:
          minimum: 0
          maximum: 100
          type: integer
          format: int32
          example: 75
        reportedAt:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        flavour:
          $ref: '#/components/schemas/WaterFlavourDto'
      required: [ fullGallons, emptyGallons, waterLevel, reportedAt, flavour ]
    WaterStateDetail:
      type: object
      properties:
        waterState:
          $ref: '#/components/schemas/WaterStateDto'
        id:
          type: integer
          format: int64
          example: 1
        reportedBy:
          type: string
          example: "John Doe"
      required: [ waterState, id ]
    WaterReportKind:
      type: string
      enum: [ PERCENTAGE, SWAP, REFILL ]
    WaterReportDto:
      type: object
      properties:
        kind:
          $ref: '#/components/schemas/WaterReportKind'
        value:
          description: |
            The level of water in the gallon, as a percentage. Only applicable for PERCENTAGE reports.
          type: integer
          format: int32
          example: 75
        flavourId:
          description: |
            The flavour of the new gallon. Only applicable for SWAP reports.
          type: integer
          format: int64
          example: 1
      required: [ kind ]
    WaterReportDetail:
      type: object
      properties:
        waterReport:
          $ref: '#/components/schemas/WaterReportDto'
        id:
          type: integer
          format: int64
          example: 1
        reportedBy:
          type: string
          example: "John Doe"
        reportedAt:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
      required: [ waterReport, id, reportedAt ]

    WaterFlavourDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Regular"
        inactive:
          type: boolean
          default: false
          example: false
      required: [ id, name, inactive ]
